# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 110610f40337996850dbaaa25b2d69fa92b0ac1a9f289d85dbedca12f8695e04a4ad9fd62ab25ad3cfe85e5ac4f7ad5d3b06d78909341accf1d2bce78af4b1fe

test:
  secret_key_base: 32c00b225a263c977829d65e8bbc35b2f8eb8634934d69c8b744c6d1bde710dd3d25f39371b566e9010afddd5a163e306e9a13b76e0043e9059fa180d18b9526

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
